#! /bin/sh
#
# Very basic deployment script
#

APPPATH=src/kadist/base
BASE=${HOME}/${APPPATH}

. $HOME/env/django/bin/activate

$BASE/manage.py collectstatic --noinput
git stash

#echo "******** Synchronizing with gnozyme..."
#rsync --bwlimit=90 -av -F ${BASE}/ gnozyme:${APPPATH}/

echo "******** Synchronizing with cinecast..."
rsync --bwlimit=90 -av -F ${BASE}/ cinecast:${APPPATH}/

git stash pop
