#! /bin/sh

export LC_ALL=en_US 

echo "Removing current db..."
rm db.sqlite
echo "syncdb..."
python ./manage.py syncdb --noinput
echo "Creating user k..."
python ./manage.py createsuperuser --username=k --email=k@k.org
